// 说明我们使用的是第 3 版的 protobuf 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: geecachepb/geecachepb.proto

// 给这份契约起个包名

package geecachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. 定义请求结构体（类似 Go 的 struct）
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 注意：这里的 = 1, = 2 不是赋值！而是给字段贴上“位置标签”。
	// 压缩数据时，它只传标签号 1 和 2，不传变量名，所以体积极小！
	Group         string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_geecachepb_geecachepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geecachepb_geecachepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_geecachepb_geecachepb_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 2. 定义响应结构体
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes 对应 Go 里面的 []byte
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_geecachepb_geecachepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geecachepb_geecachepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_geecachepb_geecachepb_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_geecachepb_geecachepb_proto protoreflect.FileDescriptor

const file_geecachepb_geecachepb_proto_rawDesc = "" +
	"\n" +
	"\x1bgeecachepb/geecachepb.proto\x12\n" +
	"geecachepb\"4\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value2D\n" +
	"\n" +
	"GroupCache\x126\n" +
	"\x03Get\x12\x16.geecachepb.GetRequest\x1a\x17.geecachepb.GetResponseB\x1dZ\x1bmony-cache_final/geecachepbb\x06proto3"

var (
	file_geecachepb_geecachepb_proto_rawDescOnce sync.Once
	file_geecachepb_geecachepb_proto_rawDescData []byte
)

func file_geecachepb_geecachepb_proto_rawDescGZIP() []byte {
	file_geecachepb_geecachepb_proto_rawDescOnce.Do(func() {
		file_geecachepb_geecachepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geecachepb_geecachepb_proto_rawDesc), len(file_geecachepb_geecachepb_proto_rawDesc)))
	})
	return file_geecachepb_geecachepb_proto_rawDescData
}

var file_geecachepb_geecachepb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geecachepb_geecachepb_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: geecachepb.GetRequest
	(*GetResponse)(nil), // 1: geecachepb.GetResponse
}
var file_geecachepb_geecachepb_proto_depIdxs = []int32{
	0, // 0: geecachepb.GroupCache.Get:input_type -> geecachepb.GetRequest
	1, // 1: geecachepb.GroupCache.Get:output_type -> geecachepb.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geecachepb_geecachepb_proto_init() }
func file_geecachepb_geecachepb_proto_init() {
	if File_geecachepb_geecachepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geecachepb_geecachepb_proto_rawDesc), len(file_geecachepb_geecachepb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geecachepb_geecachepb_proto_goTypes,
		DependencyIndexes: file_geecachepb_geecachepb_proto_depIdxs,
		MessageInfos:      file_geecachepb_geecachepb_proto_msgTypes,
	}.Build()
	File_geecachepb_geecachepb_proto = out.File
	file_geecachepb_geecachepb_proto_goTypes = nil
	file_geecachepb_geecachepb_proto_depIdxs = nil
}
